spring.application.name=recipe book

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_book
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

app.storage.s3.access-key=minioadmin
app.storage.s3.secret-key=minioadmin
app.storage.s3.region=us-east-1
app.storage.s3.bucket=recipes
app.storage.s3.endpoint=http://localhost:9000
app.storage.s3.public-url-prefix=http://localhost:9000/recipes

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB